version: '3'
services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=user
      - MYSQL_USER=gorm
      - MYSQL_PASSWORD=gorm
      - MYSQL_ROOT_PASSWORD="17356269010"
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379
